#!/usr/bin/env python
#
# Copyright 2012 Nathaniel McCallum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import os
import uuid
import sys

UUID_DIR = "/var/lib/census"
UUID_FILE = os.path.join(UUID_DIR, "uuid")
MACHINEID_FILE = "/etc/machine-id"

if not os.path.isdir(UUID_DIR):
    os.mkdir(UUID_DIR)
    os.chown(UUID_DIR, 0, 0)
    os.chmod(UUID_DIR, 0o700)

try:
    fd = os.open(UUID_FILE, os.O_WRONLY | os.O_CREAT | os.O_EXCL)
    data = str(uuid.uuid4())
    while True:
        written = os.write(fd, data)
        if written < 0:
            sys.exit(1)
        data = data[written:]
        if not data:
            break
    os.close(fd)
except OSError:
    pass

data = {}
try:
    with open(UUID_FILE) as f:
        data["uuid"] = f.read().strip()
except IOError:
    pass

try:
    with open(MACHINEID_FILE) as f:
        data["machine-id"] = f.read().strip()
except IOError:
    pass

print(json.dumps(data))
